// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyNLRhkmonD7Icm1YVCIar3Fj_TzATK5o',
    appId: '1:1007891704462:web:c5f213d1479cf05668b7df',
    messagingSenderId: '1007891704462',
    projectId: 'ecom-app-firebase',
    authDomain: 'ecom-app-firebase.firebaseapp.com',
    storageBucket: 'ecom-app-firebase.appspot.com',
    measurementId: 'G-24CMJL1ZL1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJH5apzG4q4v5xkWpullrLkW9rqTl5WAE',
    appId: '1:1007891704462:android:ae201e5b696af40468b7df',
    messagingSenderId: '1007891704462',
    projectId: 'ecom-app-firebase',
    storageBucket: 'ecom-app-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtV-8whhQmPBQNrbSvWj3yjeQgptNaXWY',
    appId: '1:1007891704462:ios:4c7b4f67cd9a67fc68b7df',
    messagingSenderId: '1007891704462',
    projectId: 'ecom-app-firebase',
    storageBucket: 'ecom-app-firebase.appspot.com',
    iosBundleId: 'com.example.eComAppFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtV-8whhQmPBQNrbSvWj3yjeQgptNaXWY',
    appId: '1:1007891704462:ios:904d9f8f527edf7668b7df',
    messagingSenderId: '1007891704462',
    projectId: 'ecom-app-firebase',
    storageBucket: 'ecom-app-firebase.appspot.com',
    iosBundleId: 'com.example.eComAppFirebase.RunnerTests',
  );
}
